# Generated by Django 5.1.5 on 2025-03-22 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminMain',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.EmailField(default='admin@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
                ('profilepic', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='auction',
            fields=[
                ('auctionid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('auctionamount', models.IntegerField()),
                ('startdate', models.TextField(null=True)),
                ('enddate', models.TextField(null=True)),
                ('auctionstatus', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('imagename', models.TextField(max_length=50)),
                ('imageurl', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('status', models.IntegerField(default=1)),
                ('addeddate', models.DateField(auto_now=True)),
                ('totaldownloads', models.IntegerField(default=0)),
                ('totalviews', models.IntegerField(default=0)),
                ('freePaid', models.BooleanField(default=False)),
                ('mrp', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('inauction', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('bidid', models.AutoField(primary_key=True, serialize=False)),
                ('bidprice', models.IntegerField()),
                ('bidtime', models.DateTimeField(auto_now=True)),
                ('auctionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.auction')),
                ('imageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='imageid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image'),
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=50)),
                ('stateid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.TextField(max_length=50)),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='subcategoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subcategory'),
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('threadid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('imageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.EmailField(default='megha@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.TextField(max_length=50)),
                ('bio', models.TextField(default='Hello', max_length=200)),
                ('regDate', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('identity', models.BooleanField(default=False)),
                ('coverpic', models.ImageField(default='images/static-1.jpg', upload_to='images/')),
                ('profilepic', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('cityid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city')),
            ],
        ),
        migrations.CreateModel(
            name='threadcomment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=50)),
                ('threadid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.thread')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentamount', models.IntegerField()),
                ('paymentdate', models.DateTimeField(auto_now=True)),
                ('bidid', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bid')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(auto_now=True)),
                ('imageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('followid', models.AutoField(primary_key=True, serialize=False)),
                ('followersid', models.IntegerField()),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='bidwinner',
            fields=[
                ('winid', models.AutoField(primary_key=True, serialize=False)),
                ('bidamount', models.IntegerField()),
                ('paymentstatus', models.IntegerField(default=0)),
                ('auctionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.auction')),
                ('imageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='auction',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wishlistid', models.AutoField(primary_key=True, serialize=False)),
                ('imageid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.image')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
