# Generated by Django 5.1.5 on 2025-03-28 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bidid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentamount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentdate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='userid',
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='orderes',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentamount', models.IntegerField()),
                ('createdDt', models.DateField(auto_now=True)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.image')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
