# Generated by Django 5.1.5 on 2025-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_payment_bidid_remove_payment_paymentamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('receiverid', models.IntegerField()),
                ('senderid', models.IntegerField()),
                ('message', models.TextField(default=True, max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('createddt', models.DateField(auto_now=True)),
            ],
        ),
    ]
