from django.urls import path
from .import views

urlpatterns = [
    path("",views.home,name="home"),
    path("login",views.login,name="login"),
    path("logout",views.logout,name="logout"),
    path("register",views.register,name="register"),
    path("myProfile",views.myProfile,name="myProfile"),
    path("imageInsert",views.imageInsert,name="imageInsert"),
    path("updProfile",views.updProfile,name="updProfile"),
    path("delImage",views.delImage,name="delImage"),
    path("displayImage",views.displayImage,name="displayImage"),
    path("follow",views.followUser,name="follow"),
    path("unfollow",views.unfollowUser,name="unfollow"),
    path("otherProfile",views.otherProfile,name="otherProfile"),
    path("imageDetails",views.imageDetails,name="imageDetails"),
    path("likeImage",views.likeImage,name="likeImage"),
    path("unlikeImage",views.unlikeImage,name="unlikeImage"),
    path("download_image",views.download_image,name="download_image"),
    path("wishlists",views.wishlists,name="wishlists"),
    path("liveAuction",views.liveAuction,name="liveAuction"),
    path("createAuction",views.createAuction,name="createAuction"),
    path("auctionDetails",views.auctionDetails,name="auctionDetails"),
    path("create_order", views.create_order, name="create_order"),
    path("create_order2", views.create_order2, name="create_order2"),
    path("verify_payment", views.verify_payment, name="verify_payment"),
    path("success", views.success, name="success"),
    path("myAuction",views.myAuction,name="myAuction"),
    path("myOrder",views.myOrder,name="myOrder"),
    path("delbid",views.delbid,name="delbid"),
    path("contact",views.contact,name="contact"),
    path("updImage",views.updImage,name="updImage"),
    path("addThread",views.addThread,name="addThread"),
    path("forgetPwd",views.forgetPwd,name="forgetPwd"),
]